package sh

import "strings"

Header :: [
	"#!/bin/sh",
	"# AUTOGENERATED",
]

Script :: {
	debug: *false | bool
	cmds: [...Command]
	compiled: _eval

	_flags: "e"
	if debug {
		_flags: "ex"
	}
	_header = Header + ["set -\(_flags)"]
	_eval = strings.Join(_header+[ c._eval for c in cmds ], "\n")
}
